### ISSUE TITLE
why use Da_pose?

### ISSUE THREAD

**Issue by surheaven** [apple/ml-neuman#21]
In paper, I only find " In comparison to the traditional T-pose, Da-pose avoids volume collision when warping from observation space to canonical space for the legs." But I can't understand this. Why is there volume collision during warping?

**Comment by jiangwei221** [comment]
Assume we use T-pose as canonical pose, and we want to render a human in a walking pose. Now, consider the samples in observation space that are 30cm far from the left leg, if we warp these samples to the T-pose, they may fall inside the volume of the right leg. Because in T-pose, two legs are very close to each other. This will cause some ghosting effects in the final rendering. 
Da-pose avoids this volume collision by increase the distance between two legs. This is not a perfect solution, but a simple trick to avoids artifacts when dealing with ill-conditioned volume warping.

**Comment by surheaven** [comment]
Thanks a lot!

**Comment by litchisea** [comment]
How to use T-pose? I want to try using T-pose
