### ISSUE TITLE
Is there any details of learned human models can be reposed to novel driving motions

### ISSUE THREAD

**Issue by APeiZou** [apple/ml-neuman#26]
@jiangwei221  Hello,  Is there any details of learned human models can be reposed to novel driving motions?

**Comment by jiangwei221** [comment]
You can have a look at the script: https://github.com/apple/ml-neuman/blob/main/render_reposing.py
The important part is that you need to manually align the human to the scene point cloud. The reason is that the human from AMASS dataset may have different scales and orientations. Check `get_manual_alignment` function.

**Comment by APeiZou** [comment]
@jiangwei221  How are the values of these variables obtained in get_manual_alignment function
 manual_trans = np.array([0.08, 0.12, 0.4])                                    
 manual_rot = np.array([95.8, 10.4, 1.8]) / 180 * np.pi                         
 manual_scale = 0.14

**Comment by jiangwei221** [comment]
Open the scene point cloud and the human in Blender, and manually adjust the transformations.

**Comment by APeiZou** [comment]
in this read_human_poses  function  why poses[:, 66:] = 0
