### ISSUE TITLE
GPU numbers and hours

### ISSUE THREAD

**Issue by Jia-Wei-Liu** [apple/ml-neuman#5]
Hi! Thanks for releasing this wonderful work!

I wonder how many GPUs and what types of GPUs are you using to train the 2 stages, and how long does it take to train the background part and human body part? Thank you!

Best regards!

**Comment by jiangwei221** [comment]
We used single 32GB ram V100. First stage can fully utilize the GPU and costs around 48 hours. Because the closest point finding operation is done on CPU, so the second stage won't fully utilize the GPU, and costs around 120 hours. In total that's around 7 days.

**Comment by Jia-Wei-Liu** [comment]
Thanks much for the quick reply! Does the first / second stage support multi-gpu training?

**Comment by jiangwei221** [comment]
Our current implementation does't support multi-GPU training. The first stage should be easily extendable with multiple GPUs. Second stage probably needs some extra cares, e.g. moving ray generation into data loader, closest point finding, etc.

**Comment by Jia-Wei-Liu** [comment]
Got it! Thanks much!

**Comment by buaacyw** [comment]
Hi! I have changed the closest point finding into GPU mode as below:
```
def warp_samples_gpu(pts, verts, T):
    res = torch.cdist(pts, verts)
    res = torch.argmin(res,dim=1)
    T_inv = torch.inverse(T)
    return T_inv[res] 
```
This is not as accurate as the original method but it raises about 50% training speed. And the experiment result is the same since non-rigid deformation can adjust it.
To use this, simply change this [method](https://github.com/apple/ml-neuman/blob/84d4685074327227457276f1b60d467f3dab1211/trainers/human_nerf_trainer.py#L266) into 
`          Ts = ray_utils.warp_samples_gpu(pts=human_pts, verts=mesh[0], T=raw_Ts[0])
`

**Comment by buaacyw** [comment]
> Our current implementation doesn't support multi-GPU training. The first stage should be easily extendable with multiple GPUs. Second stage probably needs some extra cares, e.g. moving ray generation into data loader, closest point finding, etc.

@jiangwei221 
Hi, I have a question: why should ray generation be moved into data loader for the Second stage, but no need for the First stage? I think you are mentioning this [method](https://github.com/apple/ml-neuman/blob/84d4685074327227457276f1b60d467f3dab1211/utils/ray_utils.py#L96). I'm new to DDP and I think we don't need to move ray generation method into data loader for both stage. Since DistributedSampler guarantees different ray origin and direction is loaded for different GPUs.

**Comment by jiangwei221** [comment]
Thanks for sharing! This is very useful!

**Comment by jiangwei221** [comment]
> > Our current implementation doesn't support multi-GPU training. The first stage should be easily extendable with multiple GPUs. Second stage probably needs some extra cares, e.g. moving ray generation into data loader, closest point finding, etc.
> 
> @jiangwei221 Hi, I have a question: why should ray generation be moved into data loader for the Second stage, but no need for the First stage? I think you are mentioning this [method](https://github.com/apple/ml-neuman/blob/84d4685074327227457276f1b60d467f3dab1211/utils/ray_utils.py#L96). I'm new to DDP and I think we don't need to move ray generation method into data loader for both stage.

Actually, I'm not very familiar with DDP. When I replied I was thinking this lone of code:https://github.com/apple/ml-neuman/blob/84d4685074327227457276f1b60d467f3dab1211/trainers/human_nerf_trainer.py#L353, I was not sure whether the gradients will sync in this style, also the gradient w.r.t the SMPL parameters? Just a concern, but I don't have hands on.

**Comment by buaacyw** [comment]
Thanks for your quick reply! I will try to figure it out.

**Comment by buaacyw** [comment]
> > > Our current implementation doesn't support multi-GPU training. The first stage should be easily extendable with multiple GPUs. Second stage probably needs some extra cares, e.g. moving ray generation into data loader, closest point finding, etc.
> > 
> > 
> > @jiangwei221 Hi, I have a question: why should ray generation be moved into data loader for the Second stage, but no need for the First stage? I think you are mentioning this [method](https://github.com/apple/ml-neuman/blob/84d4685074327227457276f1b60d467f3dab1211/utils/ray_utils.py#L96). I'm new to DDP and I think we don't need to move ray generation method into data loader for both stage.
> 
> Actually, I'm not very familiar with DDP. When I replied I was thinking this lone of code:
> 
> https://github.com/apple/ml-neuman/blob/84d4685074327227457276f1b60d467f3dab1211/trainers/human_nerf_trainer.py#L353
> 
> , I was not sure whether the gradients will sync in this style, also the gradient w.r.t the SMPL parameters? Just a concern, but I don't have hands on.

Hi! I think this method is fine. I can't figure out the reason why it may affect the SMPL parameters (if you mean poses and betas) since it hasn't been calculated with SMPL parameters. 
And I think using the origin CPU mode closest point finding is also fine in DDP. They are calculated on the CPU. Although they are slow, they don't affect DDP. 
If I'm wrong, please tell me. Thanks!

**Comment by Alexdruso** [comment]
@buaacyw if you have a distributed version of the code, could you please share it? Thanks for the code snippet to warp the samples on GPU btw!

**Comment by Alexdruso** [comment]
@buaacyw any update? I was trying to parallelize by myself, but even with the DataParallel wrapper the code gets stuck at loss_func in my case

**Comment by litchisea** [comment]
> @buaacyw any update? I was trying to parallelize by myself, but even with the DataParallel wrapper the code gets stuck at loss_func in my case

loss=NAN?
